import type { NextPage, GetServerSideProps } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Transfer to Ladok</h1>

        <p className={styles.description}>
          <small>
            In the next page you will need to authorize to begin using this app
          </small>
        </p>

        <Link href="/api/auth">
          <a className={styles.card}>Authorize &rarr;</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
