import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { withSessionSsr } from "lib/withSession";

const _getServerSideProps: GetServerSideProps = async (context) => {
  if (context.req.session) {
    const { accessToken } = context.req.session;

    if (accessToken) {
      // TODO: More advanced check
      return {
        props: {
          aktivitetstillfalle: [
            {
              name: "SF2743 TEN1: 2022-01-17",
              id: "b00e392e-520c-11ec-a5bb-5f5e44dd4232",
            },
          ],
          kurstillfalle: [
            {
              name: "SF2743 HT21-2",
              modules: [
                {
                  id: "SF2743",
                  code: "TEN1",
                  name: "Examination",
                },
              ],
            },
          ],
        },
      };
    }
  }

  return {
    redirect: {
      destination: `/unauthenticated?courseId=${context.query.courseId}`,
      permanent: false,
    },
  };
};

export const getServerSideProps = withSessionSsr(_getServerSideProps);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Transfer to Ladok!</h1>

        <div>
          <p>Choose what do you want to grade</p>
          <h2>Examinations</h2>
          <ul>
            <li>SF2743 TEN1: 2022-01-17</li>
          </ul>

          <h2>Modules</h2>
        </div>
      </main>
    </div>
  );
};

export default Home;
